onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
  - sharp
  - unrs-resolver

overrides:
  axios@<0.30.0: '>=0.30.0'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  form-data@<2.5.4: '>=2.5.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  xml2js@<0.5.0: '>=0.5.0'
